spring.application.name=bff
# --- H2 (in-memory) ---

rsa.public-key=file:keys/public.pem
rsa.private-key=file:keys/private.pem

spring.datasource.url=jdbc:h2:mem:kevdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# Let Hibernate create/update tables from your @Entity classes
spring.jpa.hibernate.ddl-auto=update

# Show SQL in logs (optional)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Enable H2 console (optional, useful for debugging)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Ensure schema is initialized after JPA (often helps in Boot 3/4 setups)
spring.jpa.defer-datasource-initialization=true
#resource is on port 8081
server.port=8080
logging.level.org.springframework.security=DEBUG

#ai.api.key=${OPENAI_KEY}
ai.api.key=${OPENAI_KEY}
ai.api.baseUrl=https://api.openai.com/v1


#curl -s "https://raw.githubusercontent.com/cisagov/kev-data/develop/known_exploited_vulnerabilities.json"
external.api.baseUrl=https://api.open-meteo.com/v1/forecast?latitude=55.6761&longitude=12.5683&current_weather=true
