
#upstream is the nginx load balancing module, Nginx keeps the
#32 idle reusable connections open

#proxy pass to the backend is a part of the nginx reverse proxy module
# it enables the forwarding of requests to the backend and acts as a gateway in BFF style (backend for frontend)

#$remove_addr is the client IP seen by nginx
#$proxy add x forwarded for is the chain of IPS
#proxy_set_header Connection "";
# proxy_buffering off;
# are nginx proxu module behavior controls, they disable connection after header forwarding
# disvable response buffering when streaming and in auth flow


# Then we route to the fallback, if something is not found, fallback to the index.html
# most are nginx build in modules and routing, proxy and variables.
# networking with docker ( linux needs the bridge alternative)
# so that means, when the nginx image runs in the container, it gets the variables from there, and not from the host machine
upstream backend {
    server 172.17.0.1:8080;
    keepalive 32;
}

server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location ~ ^/(api|login|logout|oauth2|.well-known/jwks.json) {
        proxy_pass http://backend;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Connection "";
        proxy_buffering off;
    }

    location / {
        try_files $uri /index.html;
    }
}